import { useEffect, useState } from 'react'
import type { Question, SchemaCatalog } from '../data/fixtures'
import { validatorClient, shouldAutoStartValidator } from '../worker/validatorClient'
import type { JudgeResult } from '../lib/types'
import { ResultView } from './ResultView'
import { AstTree } from './AstTree'
import { matchPhrases } from '../motion/intro'

export function Inspector({ question, schema }: { question: Question; schema: SchemaCatalog }) {
  const [live, setLive] = useState<JudgeResult | null>(null)
  const [error, setError] = useState<string | null>(null)

  useEffect(() => {
    setLive(null)
    setError(null)
    if (question.safety_status === 'llm_declined') return
    if (!shouldAutoStartValidator()) return // 390px spine: stays on RECORDED until the console is opened
    let cancelled = false
    validatorClient.ready.then(() =>
      validatorClient
        .judge(question.sql, 'current')
        .then((r) => { if (!cancelled) setLive(r) })
        .catch((e) => { if (!cancelled) setError(e.message) }),
    )
    return () => { cancelled = true }
  }, [question.sql, question.safety_status])

  const links = matchPhrases(question.question, question.sql, schema.approved_views)
  const identical = live && live.sql.replace(/\s+/g, ' ').trim() === question.sql.replace(/\s+/g, ' ').trim()

  return (
    <div className="inspector">
      <div className="block">
        <h4>Question &amp; assumptions</h4>
        <p className="human" style={{ fontSize: 18 }}>
          {renderLinkedQuestion(question.question, links)}
        </p>
        {question.safety_status === 'llm_declined' ? (
          <p className="dim">Claude refused. The validator never had to decide.</p>
        ) : (
          <p className="dim" style={{ fontSize: 13 }}>{question.assumptions}</p>
        )}
        <p className="mono dim" style={{ fontSize: 12 }}>cost · ${question.cost_usd.toFixed(6)}</p>
        <p className="mono" style={{ fontSize: 12 }}>
          {question.safety_status === 'llm_declined' ? <span className="dim">declined by Claude</span> : <span className="lime">validated</span>}
        </p>
      </div>

      <div className="block">
        <h4>SQL</h4>
        {question.safety_status === 'llm_declined' ? (
          <p className="dim" style={{ fontSize: 13 }}>no SQL produced</p>
        ) : (
          <>
            <div className="sql-block mono">{question.sql}</div>
            <div className="diff-gutter">as stored · regenerated by the backend</div>
            {error && <p className="dim" style={{ fontSize: 12 }}>{error}</p>}
            {live && (
              <>
                <div className="sql-block mono" style={{ marginTop: 8, fontVariationSettings: "'wdth' 75" }}>{live.sql}</div>
                <div className="diff-gutter">
                  {identical ? 'regenerated again in your browser · identical' : 'regenerated again in your browser · differs (see highlighted characters)'}
                </div>
              </>
            )}
          </>
        )}
      </div>

      <div className="block">
        <h4>Approved views &amp; AST</h4>
        <ul className="views-list">
          {schema.approved_views.map((v) => (
            <li key={v} className={live?.referencedViews.includes(v) ? 'lit' : ''}>{v}</li>
          ))}
        </ul>
        {live?.ast && <AstTree ast={live.ast} />}
      </div>

      <div className="block">
        <h4>Result</h4>
        {question.safety_status === 'llm_declined' ? (
          <p className="dim" style={{ fontSize: 13 }}>n/a</p>
        ) : (
          <ResultView columns={question.columns} rows={question.rows} truncationNote={question.question.includes('189') ? undefined : undefined} />
        )}
      </div>
    </div>
  )
}

function renderLinkedQuestion(question: string, links: { phrase: string; kind: 'derived' | 'annotation' }[]) {
  const byWord = new Map(links.map((l) => [l.phrase.toLowerCase(), l.kind]))
  return question.split(/(\s+)/).map((tok, i) => {
    const bare = tok.replace(/[^A-Za-z0-9]/g, '')
    const kind = byWord.get(bare.toLowerCase())
    if (!kind) return tok
    return <span key={i} className={`hl ${kind}`}>{tok}</span>
  })
}
